version: '3.8'

services:
  postgres:
    container_name: postgresdb1
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: node:latest
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  db_data:
